fixbroker: fix crash in cancel_fix method
Fixed this crash caused by using undefined attribute:

Traceback (most recent call last):
  File "./iq-fix_test-003.py", line 1203, in <module>
    sys.exit(main(sys.argv))
  File "./iq-fix_test-003.py", line 1194, in main
    cerebro.run()
  File "C:\Python27\lib\site-packages\backtrader\cerebro.py", line 1127, in run
    runstrat = self.runstrategies(iterstrat)
  File "C:\Python27\lib\site-packages\backtrader\cerebro.py", line 1295, in runstrategies
    self._runnext(runstrats)
  File "C:\Python27\lib\site-packages\backtrader\cerebro.py", line 1626, in _runnext
    strat._next()
  File "C:\Python27\lib\site-packages\backtrader\strategy.py", line 325, in _next
    super(Strategy, self)._next()
  File "C:\Python27\lib\site-packages\backtrader\lineiterator.py", line 266, in _next
    self.next()
  File "./iq-fix_test-003.py", line 935, in next
    self.cancel(self.stop_orders[stock])
  File "C:\Python27\lib\site-packages\backtrader\strategy.py", line 748, in cancel
    self.broker.cancel(order)
  File "C:\Python27\lib\site-packages\backtrader\brokers\fixbroker.py", line 412, in cancel
    _order.cancel_fix(self.app)
  File "C:\Python27\lib\site-packages\backtrader\brokers\fixbroker.py", line 148, in cancel_fix
    fix.Session.sendToTarget(msg, app.sessionID)
  File "C:\Python27\lib\site-packages\quickfix.py", line 39558, in <lambda>
    __getattr__ = lambda self, name: _swig_getattr(self, Application, name)
  File "C:\Python27\lib\site-packages\quickfix.py", line 83, in _swig_getattr
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))
AttributeError: 'Application' object has no attribute 'sessionID'

Signed-off-by: Ed Bartosh <bartosh@gmail.com>