fixbroker: fix crash caused by starting two iqfix apps
broker.start() method is called from core of backtrader.
Calling it in FixBroker __init__ creates duplicate thread with
iqfix App conflicting with the main one and causing tracebacks
like this one:

Traceback (most recent call last):
  File "./bt-ib-fix.py", line 174, in <module>
    sys.exit(main(sys.argv))
  File "./bt-ib-fix.py", line 171, in main
    cerebro.run()
  File "backtrader/cerebro.py", line 1127, in run
    runstrat = self.runstrategies(iterstrat)
  File "backtrader/cerebro.py", line 1295, in runstrategies
    self._runnext(runstrats)
  File "backtrader/cerebro.py", line 1626, in _runnext
    strat._next()
  File "backtrader/strategy.py", line 325, in _next
    super(Strategy, self)._next()
  File "backtrader/lineiterator.py", line 268, in _next
    self.nextstart()  # only called for the 1st value
  File "backtrader/lineiterator.py", line 342, in nextstart
    self.next()
  File "./bt-ib-fix.py", line 87, in next
    order = self.sell(self.data0, size=1) #, price=55, exectype=bt.Order.Limit) #exectype=bt.Order.Stop,
  File "backtrader/strategy.py", line 945, in sell
    **kwargs)
  File "backtrader/brokers/fixbroker.py", line 467, in sell
    exectype, valid, tradeid, **kwargs)
  File "backtrader/brokers/fixbroker.py", line 452, in _submit
    order.submit_fix(self.app)
  File "backtrader/brokers/fixbroker.py", line 133, in submit_fix
    fix.Session.sendToTarget(self.msg, app.session_id)
ValueError: invalid null reference in method 'Session_sendToTarget', argument 2 of type 'FIX::SessionID const &'

Signed-off-by: Ed Bartosh <bartosh@gmail.com>