fixbroker: check if StopPx is in the message
It's possible that StopPx tag is missing from the
execution reports about STOP orders.
This can cause crashes like this:
EXCEPTION: Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\backtrader\brokers\fixbroker.py", line 146, in wrapper
    return func(*args, **kwds)
  File "C:\Python27\lib\site-packages\backtrader\brokers\fixbroker.py", line 316, in fromApp
    price = get_value(message, fix.StopPx())
  File "C:\Python27\lib\site-packages\backtrader\brokers\fixbroker.py", line 139, in get_value
    message.getField(tag)
  File "C:\Python27\lib\site-packages\quickfix.py", line 1236, in getField
    return _quickfix.FieldMap_getField(self, *args)
FieldNotFound: Field not found

Fixed this by checking if StopPx tag is in the message
before trying to get its value.

Signed-off-by: Ed Bartosh <bartosh@gmail.com>